### PR TITLE
Add more keywords and highlight mismatching brackets

### PR DESCRIPTION
**Pull request by annarailton**
Hi Edoardo,

I made some small changes to your `.sublime-syntax` file. 

Not worked out how to do more fancy stuff like highlighting class names yet :disappointed: Will open another PR if I ever get round to that!

Anna

### CODE REVIEW

**Comment by edoardopirovano** [comment]
Hi Anna,

Nice to see someone using this (wasn't expecting anyone to, or I would have made it a bit more complete!). LGTM, I'll merge.

Incidentally, there are probably better ways of getting Sublime syntax highlighting now that we have more grammars for other IDEs (when I started this three years ago, QL4E was the only IDE integration). In particular, I think VSCode uses TextMate grammars, which Sublime also supports. So perhaps it would be possible to simply re-use that, and avoid having to maintain this. Might be worth looking into.

Edoardo

**Comment by annarailton** [comment]
Cheers Edoardo.

I found a `ql.tmLanguage.yml` file used for VSCode, e.g. 

```YAML
  # A simple-id followed by a `::` is a module qualifier.
  module-qualifier:
    match: '(?#simple-id) (?=\s*\:\:)'
    name: entity.name.type.namespace.ql
```
but couldn't work out how to convert it to the XML version of `tmLanguage` (or the `.sublime-syntax`) Sublime wanted. Any ideas? Working out how to write a lexer/parser for this just seems like re-inventing the wheel!

**Comment by edoardopirovano** [comment]
Hmm, this seems like a very easy problem but surprisingly doesn't seem to have got much attention. It looks like the [PackageDev](https://github.com/SublimeText/PackageDev) sublime plugin has some tooling for converting from a `.YAML-tmLanguage` file (which look a lot like the `.tmLanguage.yml` file you have there, but perhaps not exactly the same) to an XML `.tmLanguage` file. There's some documentation [here](https://github.com/SublimeText/PackageDev/wiki/Legacy-Syntax-Definitions) and [here](http://docs.sublimetext.info/en/latest/extensibility/syntaxdefs.html). Also, it looks like there's a [SublimeSyntaxConverter](https://github.com/aziz/SublimeSyntaxConvertor) tool that converts from `.tmLanguage` to `.sublime-syntax` which is the newer format recommended for Sublime Text 3. Hope that helps!

**Comment by annarailton** [comment]
OK so I've had a poke around and this should be a two step process in PackageDev. 

1. `PackageDev: Convert (YAML, JSON, PList) to.....`  and select `PLIST`. This gets you the XML `.tmLanguage` file.
2. Tools > Developer > New Syntax from ql.tmLanguage - this creates the `ql.sublime-syntax` file. 

Only problem is that first step fails on my `ql.tmLangage.yml` file ([this](https://gist.github.com/annarailton/7fa51f0316a81a6dd8819ec6e6d412fa)). If I try to go through an intermediate step e.g. JSON I get seemingly valid XML output but Step 2 fails. 

I couldn't get the `SubllimeSyntaxConverter` to build/run so that was a dead end for me. 

I'll have a poke around at home on another Sublime installation and report back (PackageDev was using some Python3.3 version of `plistlib.py` to convert to PLIST which seems.... not good).

**Comment by edoardopirovano** [comment]
I've also attempted what you described above on my Sublime installation and got the same results. Indeed, I also see log messages of PackageDev using a Python 3.3 version of `plistlib.py`, despite (to the best of my knowledge) only having Python 3.7 installed which seems odd. I'll also poke around some more when I get time.

**Comment by annarailton** [comment]
I did eventually manage to get it through the two conversion steps (had to do `true` -> `"true"` etc. for the first one, and add some closing `<key>end<\key>` tags for the second step. 

BUT the resulting `.sublime-syntax` file was just total garbage and barely worked - the current one is better. https://gist.github.com/annarailton/d9c57579d2a598c184af6a647f37ff14

Urgh!

**Comment by edoardopirovano** [comment]
Ah, that is unfortunate. Perhaps manually maintaining this file is the only way to support syntax highlighting in Sublime then 😟

**Pull request merged**
